create table if not exists public.indoor_obstacle_maps (
  id bigint generated by default as identity primary key,
  floor_id bigint not null references public.floors(id) on delete cascade,
  obstacles jsonb not null default '[]'::jsonb,
  source_images jsonb not null default '[]'::jsonb,
  generation_method text not null default 'multi-view-object-draft',
  scale_px_per_m double precision,
  is_confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (floor_id)
);

alter table public.indoor_obstacle_maps
  add column if not exists navigation_element_id integer
  references public.navigation_elements(id) on delete cascade;

alter table public.indoor_obstacle_maps
  add column if not exists camera_id text;

alter table public.indoor_obstacle_maps
  add column if not exists depth_mode text not null default 'monocular'
  check (depth_mode in ('depth', 'monocular'));

alter table public.indoor_obstacle_maps
  add column if not exists monocular_confirmed boolean not null default false;

alter table public.indoor_obstacle_maps
  drop constraint if exists indoor_obstacle_maps_floor_id_key;

create unique index if not exists indoor_obstacle_maps_navigation_element_key
on public.indoor_obstacle_maps (navigation_element_id)
where navigation_element_id is not null;

create table if not exists public.indoor_spatial_spaces (
  id bigint generated by default as identity primary key,
  navigation_element_id integer not null
    references public.navigation_elements(id) on delete cascade,
  floor_id bigint not null references public.floors(id) on delete cascade,
  camera_id text,
  space_name text not null,
  analysis_mode text not null default 'photo'
    check (analysis_mode in ('photo', 'live')),
  depth_mode text not null default 'monocular'
    check (depth_mode in ('depth', 'monocular')),
  monocular_confirmed boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (navigation_element_id)
);

create table if not exists public.indoor_room_spaces (
  id bigint generated by default as identity primary key,
  floor_id bigint not null references public.floors(id) on delete cascade,
  entrance_navigation_element_id integer
    references public.navigation_elements(id) on delete set null,
  room_name text not null,
  room_polygon jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.indoor_obstacle_maps
  add column if not exists room_space_id bigint
  references public.indoor_room_spaces(id) on delete cascade;

create index if not exists indoor_room_spaces_floor_idx
on public.indoor_room_spaces (floor_id);

alter table public.indoor_obstacle_maps enable row level security;
alter table public.indoor_spatial_spaces enable row level security;
alter table public.indoor_room_spaces enable row level security;

drop policy if exists "authenticated admins can read indoor obstacle maps"
on public.indoor_obstacle_maps;
create policy "authenticated admins can read indoor obstacle maps"
on public.indoor_obstacle_maps for select
to authenticated
using (true);

drop policy if exists "authenticated admins can write indoor obstacle maps"
on public.indoor_obstacle_maps;
create policy "authenticated admins can write indoor obstacle maps"
on public.indoor_obstacle_maps for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated admins can read indoor room spaces"
on public.indoor_room_spaces;
create policy "authenticated admins can read indoor room spaces"
on public.indoor_room_spaces for select
to authenticated
using (true);

drop policy if exists "authenticated admins can write indoor room spaces"
on public.indoor_room_spaces;
create policy "authenticated admins can write indoor room spaces"
on public.indoor_room_spaces for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated admins can read indoor spatial spaces"
on public.indoor_spatial_spaces;
create policy "authenticated admins can read indoor spatial spaces"
on public.indoor_spatial_spaces for select
to authenticated
using (true);

drop policy if exists "authenticated admins can write indoor spatial spaces"
on public.indoor_spatial_spaces;
create policy "authenticated admins can write indoor spatial spaces"
on public.indoor_spatial_spaces for all
to authenticated
using (true)
with check (true);
